@Web_HostAddress = http://localhost:5282


###
GET {{Web_HostAddress}}/AgeGroups

###

POST {{Web_HostAddress}}/AgeGroups
Content-Type: application/json

{
  "Name": "Grupa",
  "MinAge": 7,
  "MaxAge": 9
}

###

POST {{Web_HostAddress}}/AgeGroups
Content-Type: application/json

{
  "Name": "Niepoprawna grupa",
  "MinAge": 8,
  "MaxAge": 7
}

### 

// Teachers

POST {{Web_HostAddress}}/Teachers
Content-Type: application/json
{
  "FirstName": "Jan",
  "LastName": "Kowalski",
  "Email": "janek@testmail.pl",
  "PhoneNumber": "123456789",
  "DateOfBirth": "2000-01-01T00:00:00Z"
}